### ISSUE TITLE
why would fame not process all commits?

### ISSUE THREAD

**Issue by tessus** [ORESoftware/fame#6]
I'm sorry that I open an issue for a support question, but I couldn't find a forum or a support email. But maybe it's a bug, who knows.

For [one of my repos](https://github.com/tessus/db2-hash-routines.git), I get the following output:

```
$ fame
fame: SHA/Branch: HEAD
fame: Files must match at least one of: [ /.*/ ]
fame: Full branch name: master
fame: processing commit no.: 101, finished: 98.06%

[snip]
```

But github tells me there are 103 commits and `git rev-list --count HEAD` also returns 103.

**Comment by ORESoftware** [comment]
which version are you on? 

I published a bug today, I was passing `--no-merges` to the git log command to try to make it even more efficient, but that was causing the count to be below 100%.

See in your output it says 98.06%, so it's 101/103

try installing the latest version: 0.0.114, my guess is you are on 0.0.112 or 0.0.113

```
npm i -g fame@0.0.114
```

In other words, of your 103 commits, 2 commits should be merge commits, if that makes sense.

**Comment by tessus** [comment]
I just updated to 0.0.114 (I was on 0.0.111), however, the output is still the same.

Btw, `fame --version` does not show me the version, but does the same as `fame` (without any arguments).

**Comment by ORESoftware** [comment]
Yeah I need to add the version to the CLI. If your repo is public, I can take a look and see. Otherwise will see if I can replicate that.

**Comment by tessus** [comment]
Yep, the repo is public. https://github.com/tessus/db2-hash-routines.git

**Comment by ORESoftware** [comment]
Ok cool looks like the master branch, will try it

**Comment by tessus** [comment]
>Yeah I need to add the version to the CLI

Ah, ok. I saw it in help, so I thought is has been implemented. ;-)

**Comment by ORESoftware** [comment]
it's because of this:

```console
angoca at yahoo or gmail
```

if you run this:

```bash
git log --numstat --pretty='%ae' | cat
```
`
on the master branch, towards commit number 80 or so.

basically because there is whitespace in the email address, it's breaking. whitespace in email address is pretty uncommon obviously, I am not sure what that's about, might be a .mailtrap thing.

In your git log, it normally looks like this:

```
tessarek@evermeet.cx

3       4       .travis.yml
tessarek@evermeet.cx

2       2       .travis.yml
tessarek@evermeet.cx
angoca at yahoo or gmail

2       2       .travis.yml
angoca at yahoo or gmail

```

never seen an email appear like that.

I have an idea on how to fix it, which will gel with the author name solution too, so that's good, will work on it this weekend probably.

**Comment by tessus** [comment]
Ah, I see. Thanks for the info. Yeah, Andres used this weird format. I'm not sure why. His commits don't have a valid email. I hope he's changed his habit. But that's fine. It's not a bug, all good.
Thanks for looking into it. I was just puzzled because there was no output, e.g. email invalid, couldn't process this damn format.

Usually this should never happen. Maybe I should have just used a pre-commit hook that checks for a valid email (not sure how to do that with gh though). But it's obviously not your fault.

If you want, you can close this issue. I just didn't understand why 2 commits were missing. Now I do.

**Comment by ORESoftware** [comment]
Yeah the fix for author name will also fix this issue, thanks for the heads up, bugs like this are good to know about

**Comment by ORESoftware** [comment]
@tessus  the author_conf in this repo branch also solves this problem...if the email address is:

```
"angoca at yahoo or gmail"
```

then now it can handle the whitespace, whereas before it could not handle whitespace in an "email address"
